-- Real user registration fields and USER role.

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'UserRole') THEN
    ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'USER';
  END IF;
END $$;

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS "passwordHash" TEXT,
  ADD COLUMN IF NOT EXISTS name TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS city TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS state TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "profileImage" TEXT,
  ADD COLUMN IF NOT EXISTS bio TEXT,
  ADD COLUMN IF NOT EXISTS "acceptedTerms" BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS "acceptedPrivacyPolicy" BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS "lastLoginAt" TIMESTAMP(3);

ALTER TABLE users
  ALTER COLUMN role SET DEFAULT 'USER';

UPDATE users
SET role = 'USER'
WHERE role::text = 'STUDENT';

UPDATE users
SET "passwordHash" = password
WHERE "passwordHash" IS NULL AND password IS NOT NULL;
