resources:
  - ../../base

nameSuffix: -staging

patches:
  - target:
      kind: HorizontalPodAutoscaler
      name: meetpoint-api
    patch: |-
      - op: replace
        path: /spec/maxReplicas
        value: 4
